import { atom } from "jotai";
import { PropertyType } from "./types";

export const propertiesAtom = atom<PropertyType[]>([
  {
    id: 1,
    location: "New York, NY",
    city: "New York",
    state: "NY",
    type: "Apartment",
    rooms: 3,
    bathrooms: 2,
    price: 1200000,
    photos: ["/images/property1.jpg", "/images/property1-2.jpg"],
  },
  {
    id: 2,
    location: "Los Angeles, CA",
    city: "Los Angeles",
    state: "California",
    type: "House",
    rooms: 3,
    bathrooms: 2,
    price: 950000,
    photos: ["/images/property2.jpg", "/images/property2-2.jpg"],
  },
  {
    id: 3,
    location: "New York, NY",
    city: "New York",
    state: "NY",
    type: "Condo",
    rooms: 2,
    bathrooms: 2,
    price: 750000,
    photos: ["/images/property3.jpg", "/images/property3-2.jpg"],
  },
  {
    id: 4,
    location: "Los Angeles, CA",
    city: "Los Angeles",
    state: "California",
    type: "Condo",
    rooms: 1,
    bathrooms: 1,
    price: 650000,
    photos: ["/images/property4.jpg", "/images/property4-2.jpg"],
  },
  {
    id: 5,
    location: "Los Angeles, CA",
    city: "Los Angeles",
    state: "California",
    type: "Townhouse",
    rooms: 3,
    bathrooms: 2,
    price: 920000,
    photos: ["/images/property5.jpg", "/images/property5-2.jpg"],
  },
  {
    id: 6,
    location: "New York, NY",
    city: "New York",
    state: "NY",
    type: "Apartment",
    rooms: 2,
    bathrooms: 2,
    price: 900000,
    photos: ["/images/property6.jpg", "/images/property6-2.jpg"],
  },
  {
    id: 7,
    location: "San Francisco, CA",
    city: "San Francisco",
    state: "California",
    type: "Loft",
    rooms: 2,
    bathrooms: 1,
    price: 850000,
    photos: ["/images/property7.jpg", "/images/property7-2.jpg"],
  },
  {
    id: 8,
    location: "San Francisco, CA",
    city: "San Francisco",
    state: "California",
    type: "House",
    rooms: 4,
    bathrooms: 3,
    price: 1200000,
    photos: ["/images/property8.jpg", "/images/property8-2.jpg"],
  },
  {
    id: 9,
    location: "Los Angeles, CA",
    city: "Los Angeles",
    state: "California",
    type: "Mansion",
    rooms: 6,
    bathrooms: 5,
    price: 3500000,
    photos: ["/images/property9.jpg", "/images/property9-2.jpg"],
  },
  {
    id: 10,
    location: "San Diego, CA",
    city: "San Diego",
    state: "California",
    type: "House",
    rooms: 4,
    bathrooms: 3,
    price: 1450000,
    photos: ["/images/property10.jpg", "/images/property10-2.jpg"],
  },
  {
    id: 11,
    location: "New York, NY",
    city: "New York",
    state: "NY",
    type: "Condo",
    rooms: 2,
    bathrooms: 1,
    price: 700000,
    photos: ["/images/property11.jpg", "/images/property11-2.jpg"],
  },
  {
    id: 12,
    location: "New York, NY",
    city: "New York",
    state: "NY",
    type: "Townhouse",
    rooms: 4,
    bathrooms: 3,
    price: 1600000,
    photos: ["/images/property12.jpg", "/images/property12-2.jpg"],
  },
  {
    id: 13,
    location: "Los Angeles, CA",
    city: "Los Angeles",
    state: "California",
    type: "Loft",
    rooms: 2,
    bathrooms: 1,
    price: 800000,
    photos: ["/images/property13.jpg", "/images/property13-2.jpg"],
  },
  {
    id: 14,
    location: "Chicago, IL",
    city: "Chicago",
    state: "Illinois",
    type: "Condo",
    rooms: 3,
    bathrooms: 2,
    price: 750000,
    photos: ["/images/property14.jpg", "/images/property14-2.jpg"],
  },
  {
    id: 15,
    location: "Chicago, IL",
    city: "Chicago",
    state: "Illinois",
    type: "Apartment",
    rooms: 2,
    bathrooms: 1,
    price: 450000,
    photos: ["/images/property15.jpg", "/images/property15-2.jpg"],
  },
]);
